### ISSUE TITLE
 Cannot find module 'typescript-collections' for versions >1.1.4.

### ISSUE THREAD

**Issue by CaselIT** [basarat/typescript-collections#51]
Version 1.1.5, 1.1.6 and 1.1.7 cannot be loaded.

``` shell
> const coll = require('typescript-collections')
Error: Cannot find module 'typescript-collections'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at repl:1:14
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
    at bound (domain.js:280:14)
```

node version 6.6.0, installed with npm 3.10.7

**Comment by episage** [comment]
@CaselIT Thank you for quick reaction.

That's so weird. When I run `npm run all` it doesn't make `umd.js` in `dist`. When I run `npm run build` it does. `npm run build` is included in `npm run all`. 
Confused, but I'm on it. I will fix it very soon.

**Comment by episage** [comment]
Silly me! `"test": "npm run clean && npm run tsc && mocha ./dist/test/*Test.js",`

**Comment by episage** [comment]
#52

**Comment by CaselIT** [comment]
Thanks for the quick solution 👍
