### ISSUE TITLE
Error typescript-collections 404 (Not Found) with Angular 2 final

### ISSUE THREAD

**Issue by Anthony-Breneliere** [basarat/typescript-collections#53]
Hello I do have the following error after launching my project.

From an Angular 2 quick-start project, I just installed typescript-collecions:

```
GET http://localhost:63342/IMA%20Sentinel/node_modules/typescript-collections 404 (Not Found)
Error: Error: XHR error (404 Not Found) loading http://localhost:63342/IMA%20Sentinel/node_modules/typescript-collections
        at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:63342/IMA%20Sentinel/node_modules/zone.js/dist/zone.js:636:29)
        at ZoneDelegate.invokeTask (http://localhost:63342/IMA%20Sentinel/node_modules/zone.js/dist/zone.js:225:37)
        at Zone.runTask (http://localhost:63342/IMA%20Sentinel/node_modules/zone.js/dist/zone.js:125:47)
        at XMLHttpRequest.ZoneTask.invoke (http://localhost:63342/IMA%20Sentinel/node_modules/zone.js/dist/zone.js:293:33)
    Error loading http://localhost:63342/IMA%20Sentinel/node_modules/typescript-collections as "typescript-collections" from http://localhost:63342/IMA%20Sentinel/app/history.service.js
```

Here is the history.service.ts file where I use a dictionary

```
import { Injectable } from '@angular/core';
import { Dto } from './dto';
import Collections = require('typescript-collections');

@Injectable()
export class HistoryService {

  public managedDtoDico : Collections.Dictionary<number, Dto> = new Collections.Dictionary<number, Dto>();
```

The package is installed here :
[projectName]\node_modules\typescript-collections

My tsconfig.json:

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true
  }

}
```

Did I miss something ?

**Comment by Anthony-Breneliere** [comment]
Ok the folowing parameters were missing in the system.config.js : 

```
  ,
  'typescript-collections': {
    main: './dist/lib/index.js',
    defaultExtension: 'js'
  }
```
