### ISSUE TITLE
LinkedDictionary.forEach throw Error

### ISSUE THREAD

**Issue by nolazybits** [basarat/typescript-collections#97]
```
    TypeError: Cannot read property 'next' of undefined

      41 |     {
      42 |         //  @ts-ignore: we don't use the key param here
    > 43 |         this._modules.forEach(async (key: string,  module: IModule) =>
         |                                                                       ^
      44 |         {
      45 | 
      46 |         });

      at isHeadOrTailLinkedDictionaryPair (../../node_modules/typescript-collections/dist/lib/dist/lib/LinkedDictionary.js:67:1)
      at LinkedDictionary.Object.<anonymous>.require.7.LinkedDictionary.forEach (../../node_modules/typescript-collections/dist/lib/dist/lib/LinkedDictionary.js:233:1)
      at BugReport.start (src/BugReport.ts:43:71)
      at Object.<anonymous>.it (tests/unit/BurReport.test.ts:155:19)

```

**Comment by episage** [comment]
Closing this because of old age. If the issue persists, discuss it here and/or open a Pull Request please.
